Adjective-Object/good-fences-rs-core

.github/workflows/unittest.yml
`GLIBC` version in owa-build agents is lower than the ones here, because of that `*.node` files cannot be used in there.
=> Downgrade ubuntu version

__test__/index.spec.mjs, good-fences.js, src/error/mod.rs, src/evaluate_fences.rs, src/good_fences_runner.rs, src/lib.rs, src/walk_dirs.rs
Currently, `ignoredDirs` option only excludes files from being evaluated with their fence config. The problem is that even when files in `shared/.**/lib` or `dist` are not evaluated, their AST is still being parsed, considering that it is an expensive task to do, it is having an impact on performance.
- Files under matching `ignoredDirs` regexes will be ignored (sources and fences).
- Resolved import paths matching `ignoredDirs` are ignored, even if they would be violations.
=> Matching ignored dirs will be added as source files with empty impot map

.github/workflows/unittest.yml, change/@good-fences-api-c672cfce-50b8-4ace-980f-961be664715d.json
unittest is run as part of the publish flow, which is also triggered on `main`.
Therefore, the `unittest.yml` workflow does not need its own trigger on `main`.
=> Fixed action yml to avoid duplicated workflow on merge to main

Cargo.lock, Cargo.toml, change/@good-fences-api-71d55142-6b70-48ec-b328-39511e2639b6.json, good-fences.js, src/evaluate_fences.rs, src/good_fences_runner.rs, src/import_resolver.rs, src/walk_dirs.rs
Added resolver to get resolved files with extension in order to avoid files with multiple `.` on it's name to resolve a different extension:
Currently imports such as `graphql/__generated__/getBuildingQuery.interface` resolves with extension `interface` instead of `ts`.
`resolve_with_extension` uses `swc` import resolver to retrieve resolved files with the full extension of the file even when it has `.` in the name.
=> Use swc in resolve_with_extension

change/@good-fences-api-5d6cb165-1214-4a7d-aca8-f1cf100d7c5d.json, src/unused_finder/graph.rs, src/unused_finder/mod.rs, src/unused_finder/node_visitor.rs
- Added feature to track unused items within used files.
- When building report now filter used files and pull the ones that have non-empty list inside `GraphFile::unused_items`.
- Added capability to track items masked through `export ... from ...` statements.
- Resolve/Mark items as used inside `GraphFile` now return an enum if the item was created in the file or it was pulled via export/from statement.
=> enable find unused items within files

change/@good-fences-api-ad74f215-3f05-491e-a272-ead77028d8b3.json, src/unused_finder/mod.rs
Looks in cwd for a file called `.unusedignore`
Allowed items can be:
- specific file paths like `shared/internal/owa-react-hooks/src/useWhyDidYouUpdate.ts`
- glob patterns (similar to a `.gitignore` wildcard patterns) `shared/internal/owa-datetime-formatters/**`
=> Added support for `.unusedignore` file

change/@good-fences-api-8b2d7eb8-f54f-4f32-90d5-875daec6ee55.json, src/lib.rs, src/unused_finder/mod.rs
Created `UnusedFinderReport` struct:
- Instead of returning a `Vec<String>` that represents all error messages thrown during execution, now return `UnusedFinderReport`
- `UnusedFinderReport::unused_files` a vec of files marked as unused, this list is already sanitized and does not contain non-scanned files or files that match any patter in `.unusedignore` file.
- `UnusedFinderReport::unused_files_items` hashmap with **_key: file path_** and **_value: items within file that are not imported_**.
=> Added report struct to improve error handling in owa-build

change/@good-fences-api-1546b19c-4903-4575-bc49-0f8a2c53fc04.json, src/unused_finder/mod.rs, src/unused_finder/unused_finder.rs
Addresses @Adjective-Object 's comments from #64 
- Adds comments to `UnusedFinder::refresh_*` methods.
- Removes redundant property `UnusedFinder::flattened_walk_file_data` to avoid information to not be synced in `UnusedFinder::graph`
- Improves validation for max_iteration in bfs_step/frontier execution.
=> Address comments from PR #64

change/@good-fences-api-0e4ef024-a32b-4faa-a002-c007116eb92a.json, good-fences.js, src/evaluate_fences.rs, src/good_fences_runner.rs, src/import_resolver.rs, src/lib.rs, src/walk_dirs.rs
Current SWC resolver prioritizes resolving paths to `**/lib/**` files instead of using tsconfig.paths.json `compilerOptions.paths` values. This prevents devs from running good-fences accurately if they run local builds or run `yarn typecheck` since those generate files under packages `lib/` dir.
Reverting to old resolver and adding some logic to handle cases such as adding extensions to files and appending `index` whenever is needed.
=> Reverted good-fences resolver function to enable run quick checks on local environments

change/@good-fences-api-a651a4d8-d9c8-41de-a1f3-36fcfdb1edde.json, crates/unused_finder/src/core.rs, crates/unused_finder/src/unused_finder.rs
Disable per-item reporting with report_exported_items flag
This is for cleaner test reporting while debugging unused files in `unused_bin`
=> add report_exported_items flag to gate reporting exported items

change/@good-fences-api-f5109c05-4f36-4f15-8742-fb295865c36d.json, crates/import_resolver/src/swc_resolver/combined_resolver.rs, crates/import_resolver/src/swc_resolver/node_resolver.rs, crates/import_resolver/src/swc_resolver/pkgjson_exports.rs, crates/packagejson/src/packagejson.rs
Support heterogenous export maps in import_resolver and package.json
This is an export map that mixes conditional and non-conditional exports e.g.:
```json5
{
"exports": {
// non-conditional export
".": "./src/index.js"
//conditional export
"./foo": {
"import": "./src/foo.mjs"
"require": "./src/foo.cjs"
"default": "./src/foo.cjs"
}
}
}
```
=> pacakgejson, import_resolver: heterogenous export maps

Cargo.lock, change/@good-fences-api-fe0720e5-9f97-4b22-a945-20bad35635de.json, crates/import_resolver/src/swc_resolver/mod.rs, crates/import_resolver/src/swc_resolver/pkgjson_exports.rs, crates/test_tmpdir/src/lib.rs
Add utilities to import_resolver's packagejson_exports to support checking if a file is exported from a package.
This will be used by the unused_finder to determine if a file is an entrypoint to the graph walk when the package has an exports map.
In order to support tests, I also added a second map macro that does not stringify keys. This is because we want to create maps that have &'static str keys instead of String keys in the tests for is_file_exported
=> import_resolver: add and expose `is_file_exported` for checking if a file is exported from a package

Cargo.lock, Cargo.toml, change/@good-fences-api-de8779f5-235e-410b-99b3-b8a562a72db7.json, crates/ahashmap/Cargo.toml, crates/good_fences/Cargo.toml, crates/good_fences/src/get_imports/import_path_visitor.rs, crates/swc_utils_parse/Cargo.toml, crates/swc_utils_parse/src/lib.rs, crates/swc_utils_print/Cargo.toml, crates/swc_utils_print/src/lib.rs, crates/unused_finder/Cargo.toml, crates/unused_finder/src/parse/exports_visitor_runner.rs, crates/unused_finder/src/parse/exports_visitor_tests.rs
This saves between 0.5s and 1s on the end-to-end development compilation time (~25.7s ->~25.1s in my scratch testing)
This is because code normalization (not yet used) depends on the swc_ecma_minifier indirectly, which is slow to compile.
=> reduce compilation times by breaking up swc_utils

.github/workflows/unittest.yml, change/@good-fences-api-efc2f88d-514a-4a48-a185-63f4655d449d.json
Neat trick I ran into on this blog:
https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions
=> cancel old CI jobs when new PR revisions are pushed

change/@good-fences-api-144caee8-8d20-4404-9140-1c481de6e396.json, crates/unused_finder/src/cfg/mod.rs, crates/unused_finder/src/graph.rs, crates/unused_finder/src/parse/data.rs, crates/unused_finder/src/parse/exports_visitor.rs, crates/unused_finder/src/parse/exports_visitor_tests.rs, crates/unused_finder/src/report.rs, crates/unused_finder/src/test.rs, crates/unused_finder/src/unused_finder.rs, crates/unused_finder_napi/src/lib.rs
Many of the unused symbols being reported by unused finder are type declarations used by exported symbols that don't themselves have additional bundle weight implications.
This change is intended to allow these situations without having to support intra-file reference tracking.
The approach taken was to attach additional metadata to each declared export, as well as each declared re-export from another file, saying if the symbol is a type-only export.
This is later-on used to mark all type-only entrypoints in the graph with a new tag, which is used to filter them out of the report.
As part of this change, I also refactored the export tracking so that type-only re-exports would not be followed during edge traversals. This is because type-only re-exports do not have an associated bundle …
=> unused finder: support type-only exports

.github/workflows/unittest.yml, change/@good-fences-api-5a2b5160-385b-486d-aac9-b8b3a519a284.json
Removes the redundant repo clone in the repo health checks jon
=> unittest.yml: remove redundant repo clone in health checks

change/@good-fences-api-6c696660-0b84-426a-b838-398dda540094.json, package.json, yarn.lock
I ran `npm pkg fix` in repo root and committed the results
See this error log:
https://github.com/Adjective-Object/good-fences-rs-core/actions/runs/11672948170/job/32507548250#step:13:345
npm warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm warn publish errors corrected:
npm warn publish Removed invalid "scripts"
=> Run `npm pkg fix` in repo root

Cargo.lock, change/@good-fences-api-aa31c04e-9fa3-4be0-b954-b56665c76c6d.json, crates/unused_finder/Cargo.toml, crates/unused_finder/src/cfg/mod.rs, crates/unused_finder/src/graph.rs, crates/unused_finder/src/lib.rs, crates/unused_finder/src/report.rs, crates/unused_finder/src/tag.rs, crates/unused_finder/src/test.rs, crates/unused_finder/src/unused_finder.rs, crates/unused_finder_napi/src/lib.rs
This returns info on ignored files in the `report`. The intent here is to also make it possible for the consumer to show information on files that are only used in tests.
=> Return 'extra file tags' in report info

Cargo.lock, Cargo.toml, change/@good-fences-api-a7359cc9-6b5b-4355-a1c7-448c715e2197.json, crates/logger/Cargo.toml, crates/logger/src/lib.rs, crates/logger_console/Cargo.toml, crates/logger_console/src/lib.rs, crates/unused_bin/Cargo.toml, crates/unused_bin/src/main.rs, crates/unused_finder/Cargo.toml, crates/unused_finder/src/graph.rs, crates/unused_finder/src/lib.rs, crates/unused_finder/src/test.rs, crates/unused_finder/src/unused_finder.rs, crates/unused_finder/src/walk.rs, crates/unused_finder_napi/Cargo.toml, crates/unused_finder_napi/src/lib.rs
This is so it can be compiled separately. In the future, it may be referenced from other packages that want to do logging without creating dependency cyles.
=> Refactor `unused_finder/logger` into standalone package

change/@good-fences-api-a7d88fdc-f981-44c7-9d08-98ac791efdd3.json, crates/unused_finder_napi/src/lib.rs
Removes the redundant `testPathPattern` field from the napi unusedFinderConfig, and removes some of the unused serde serialization/deserialization fields from the napi types.
=> Remove redundant test pattern

Cargo.lock, change/@good-fences-api-6ffba5db-a75b-4958-8cba-3e2dea22fa8b.json, crates/logger/src/lib.rs, crates/logger_srcfile/Cargo.toml, crates/logger_srcfile/src/lib.rs, crates/unused_finder/src/lib.rs, crates/unused_finder/src/unused_finder.rs, crates/unused_finder/src/walk.rs
The overall goal of this change is to support a "sub-trait" of `logger`
that adds some src-file logging methods associated against a given
logging.
This will be used to trace issues with src files while e.g. parsing or
interpreting the structure of source files. As part of this change, the
`Sync` requirement of logger had to be dropped.
This is because the src file informatio nwe get from `swc` is
necessarially non-`Sync`/`Send`.
=> Restructure logger to enable `logger_srcfile`

Cargo.lock, change/@good-fences-api-0f6279b9-8b8a-4bab-8016-be7b09527870.json, crates/ast_name_tracker/Cargo.toml, crates/ast_name_tracker/src/lib.rs, crates/ast_name_tracker/src/visitor.rs
Adds a new crate `ast_name_tracker` for tracking declared and shadowed names in ESM snippets.
This is necessary to track any statistics on a per-symbol level without aggregating dependencies on the module-level, as it can operate on the source level.
=> ast_name_tracker: track external references in ESM snippets

.github/workflows/publish.yml, change/@good-fences-api-8147c32a-887f-40ad-9631-2868257e3b19.json, package.json
- replaces the yarn workspace publish with `napi prepublish`
- removes the default platforms from the napi platforms array (was causing redundant publishing)
=> publish.yml: dedup the default deploy platforms

.devcontainer/podman/devcontainer.json, .devcontainer/podman/patch.json, change/@good-fences-api-0596ce17-9105-4394-83a1-ffb3cce67733.json
replaces the default (pasta) with slirp4netns in the podman container.
This is a workaround to allow using the container when offline.
Note that this actually degrades network peformance for the container,
so it should be removed once the fix for pasta/podman is eventually implemented.
See: https://github.com/containers/podman/issues/23566
Note that this requires the host system to have slirp4netns installed
on fedora you can do this via `dnf install slirp4netns`
=> devcontainer.json: use slirp4netns to boot offline

Cargo.lock, change/@good-fences-api-d1c12010-0e3a-4d4d-96a9-5a84ae2d5558.json, crates/multi_err/Cargo.toml, crates/multi_err/src/lib.rs
Adds a convenience crate for combining multiple errors and results from a batch operation
=>  multi_err: new crate for combining errors 

.vscode/extensions.json, change/@good-fences-api-0e7b8ffa-fb92-4421-9d67-9c7fcfd4fd7b.json
Adds the `rust-analyzer` extension to the workspace's default installed extensions
=> .vscode: add missing rust-analyzer extension

Cargo.lock, change/@good-fences-api-83397144-820e-4f75-82b2-00d3fdc75b2e.json, crates/unused_finder/Cargo.toml, crates/unused_finder/src/graph.rs, crates/unused_finder/src/parse/data.rs, crates/unused_finder/src/unused_finder.rs
Consumes multi_err in unused_finder to report all resolution errors when something goes wrong during resolution
=> unused_finder: consume multi_err to return multiple resolution errors

change/@good-fences-api-8fcdec71-7be8-41ec-b321-840ea53cc7ec.json, crates/unused_finder/src/graph.rs
Ensures that multiple tagging passes over a graph will not overwrite previous tagged values
=>  unused_finder: ensure tagging passes don't overwrite each other 

change/@good-fences-api-2dc2fc9c-d313-4d4a-8eb2-252b3dc2767b.json, change/@good-fences-api-2dc2fc9c-d313-4d4a-8eb2-252b3dc2767c.json, change/@good-fences-api-2dc2fc9c-d313-4d4a-8eb2-252b3dc2767d.json, crates/unused_bin/src/main.rs, crates/unused_finder/src/graph.rs, crates/unused_finder/src/parse/data.rs, crates/unused_finder/src/parse/exports_visitor_tests.rs, crates/unused_finder/src/report.rs, crates/unused_finder/src/test.rs, crates/unused_finder/src/unused_finder.rs
Contains: 
- [graph: don't forget re-exported symbols!](https://github.com/Adjective-Object/good-fences-rs-core/commit/ec6d59f62fe56b1ea17f0fbbb95720fd4349badf)
- [unused_finder: adjust graph to include file tags](https://github.com/Adjective-Object/good-fences-rs-core/commit/0ac7df4c0c95951b021c797e8c055b5fecc867aa)
- [unused_finder: mark files as typeonly if their contents are typeonly](https://github.com/Adjective-Object/good-fences-rs-core/commit/edbbd6bfcb488ea52e27fe632965a8f341fd92d6)
- [unused_finder: fix tests by expanding export star during source file resolution](https://github.com/Adjective-Object/good-fences-rs-core/pull/116/commits/09265b85471e0f02df78b99a7e984c06a8e95fad)
=> Updates 2025 07 02

.devcontainer/default/container/.gitconfig, change/@good-fences-api-d123a39b-a3a3-49f6-b648-2b0ac61df85b.json, crates/unused_finder/src/parse/data.rs, crates/unused_finder/src/unused_finder.rs
- Avoids infinite loop while expanding unresolved external import
- Avoids infinite loop while expanding cyclical imports
- Adds maximum caps to all frontier traversals in graph generation and export * expansion
=> Avoid infinite loops in `export * from` expansion
